# Use a Node base image
FROM node:latest as build

# Set the working directory
WORKDIR /app

# Copy source into working directory
COPY HIVE-ui/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY HIVE-ui/ .

# Declare arguments with default values
ARG REACT_APP_API_BACKED_URL="http://localhost:8000"
ARG REACT_APP_API_MODEL_SELECTION="/models/"
ARG REACT_APP_API_MAX_GEN_TOKENS=2048
ARG REACT_APP_API_MAX_TOKENS=4096
ARG REACT_APP_API_PROMPT="You are a very intelligent AI that wants to help everyone succeed"
ARG REACT_APP_API_ANTI_PROMPT="### Instruction:"
ARG REACT_APP_API_ASSISTANT_PROMPT="### Response:"

# Set environment variables from arguments
ENV REACT_APP_API_BACKED_URL=$REACT_APP_API_BACKED_URL
ENV REACT_APP_API_MODEL_SELECTION=$REACT_APP_API_MODEL_SELECTION
ENV REACT_APP_API_MAX_GEN_TOKENS=$REACT_APP_API_MAX_GEN_TOKENS
ENV REACT_APP_API_MAX_TOKENS=$REACT_APP_API_MAX_TOKENS
ENV REACT_APP_API_PROMPT=$REACT_APP_API_PROMPT
ENV REACT_APP_API_ANTI_PROMPT=$REACT_APP_API_ANTI_PROMPT
ENV REACT_APP_API_ASSISTANT_PROMPT=$REACT_APP_API_ASSISTANT_PROMPT
RUN npm run build

# Use nginx to serve the React app
FROM nginx:alpine

# Copy the build from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]