# Use a Node base image
FROM node:latest as build

# Set the working directory
WORKDIR /app

# Copy source into working directory
COPY HIVE-ui/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY HIVE-ui/ .

# Build your app
RUN npm run build

# Use nginx to serve the React app
FROM nginx:alpine

# Copy the build from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
